api_root_path: /
artifact_infos: []
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_connection_str: '**********'
db_name: dev_db
docs_url: /docs
host: 127.0.0.1
loader_token_hashes:
- test_token_hash
log_level: info
openapi_url: /openapi.json
port: 8080
workers: 1
