accession_registry_path: /path/to/accession_registry.txt
metadata_model: /workspace/example_data/test_model.yaml
source_events_dir: /path/to/source/event/dir
submission_store_dir: /path/to/submission/store/dir
