accession_store_path: /path/to/accession_store.txt
metadata_model_path: /workspace/tests/fixtures/example_models/advanced_model.yaml
prefix_mapping:
  dataset: GHGAD
  experiment: GHGAE
  file: GHGAF
  sample: GHGAS
source_event_topic: source_events
source_event_type: source_event
submission_store_dir: /path/to/submission/store/dir
suffix_length: 8
