components:
  schemas:
    Greeting:
      description: A container storing a greeting for a specfic person incl. metadata
      properties:
        created_at:
          description: The date/time when the message was created
          format: date-time
          title: Created At
          type: string
        isinformal:
          description: Is the expression used in informal contexts?
          title: Isinformal
          type: boolean
        language:
          description: The language.
          enum:
          - Greek
          - Croatian
          - French
          - German
          title: Language
          type: string
        message:
          description: The message content.
          title: Message
          type: string
      required:
      - message
      - created_at
      - language
      - isinformal
      title: Greeting
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      description: Greet the World
      operationId: index__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Greet the world
  /greet/{name}:
    get:
      description: Greet a person by name. You may choose a formal or an informal
        greeting.The language for the greeting is configured in the backend.
      operationId: greet_greet__name__get
      parameters:
      - in: path
        name: name
        required: true
        schema:
          title: Name
          type: string
      - in: query
        name: isinformal
        required: false
        schema:
          default: true
          title: Isinformal
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Greet a person
