# Please only mention the non-default settings here:

metadata_model_path: /workspace/example_data/test_model.yaml
prefix_mapping:
  file: GHGAF
  experiment: GHGAE
  sample: GHGAS
  dataset: GHGAD

accession_store_path: /path/to/accession_store.txt
submission_store_dir: /path/to/submission/store/dir
source_events_dir: /path/to/source/event/dir
