version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3.9
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # Please adapt to package name:
        PACKAGE_NAME: "my_microservice"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    privileged: true

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # define environment variables
    environment:
      # Please adapt to package name:
      MY_MICROSERVICE_CONFIG_YAML: /workspace/.devcontainer/.dev_config.yaml
      # Used by db migration:
      DB_URL: postgresql://postgres:postgres@postgresql/postgres
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  # Please remove service dependencies that are not needed:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_fs:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    # useful ports:
      # 5672 - broker
      # 15672 - dashboard

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1
      # accessible at localhost
      HOSTNAME_EXTERNAL: localhost
      USE_SSL: "false"
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
    volumes:
      - type: volume
        source: s3_fs
        target: /tmp/localstack
        volume:
          nocopy: true
    # useful ports: 4566 - AWS API

volumes:
  postgres_fs: {}
  s3_fs: {}
  mongo_fs: {}
