name: Check if the README file is up to date

on: push

jobs:
  static-code-analysis:
    name: Check README file

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v5

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6
        with:
          python-version: '3.13'

      - name: Check README
        id: check-readme
        run: |
          ./scripts/update_readme.py --check
