name: Check if the config schema and the example are up to date

on: push

jobs:
  static-code-analysis:
    name: Check config schema and example

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6

      - name: Check config docs
        id: check-config-docs
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          ./scripts/update_config_docs.py --check
